project_name: tp
release:
  github:
    owner: minefuto
    name: tp
env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
builds:
  - main: .
    binary: tp
    ldflags:
      - -s -w
      - -X main.version={{.Tag}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
changelog:
  skip: true
archives:
  - files:
    - LICENSE*
